import CoreText
import Foundation

enum FontRegistrar {
    /// Registers Cinzel Decorative (Bold 700) from the app bundle at runtime.
    /// This avoids requiring an Info.plist `UIAppFonts` entry when the plist is generated by Xcode.
    static func registerCinzelDecorativeIfNeeded() {
        registerFontIfNeeded(filename: "CinzelDecorative-Bold", fileExtension: "ttf")
    }

    private static func registerFontIfNeeded(filename: String, fileExtension: String) {
        guard let url = Bundle.main.url(forResource: filename, withExtension: fileExtension) else {
            // If this happens, the font file likely wasn't included in the app bundle resources.
            return
        }

        var error: Unmanaged<CFError>?
        CTFontManagerRegisterFontsForURL(url as CFURL, .process, &error)
        _ = error // Keep silent in production; safe no-op if already registered.
    }
}


