import Foundation

/// Asset names used to generate a layered profile avatar.
///
/// These correspond to `Assets.xcassets/profile/{head,face}/*.{imageset}`.
/// All assets are now in .imageset folders and ready to use with Image(name).
enum ProfileAvatarAssets {
  static let heads: [String] = [
    "Bangs",
    "Bangs 2",
    "Bantu Knots",
    "Bear",
    "Bun 2",
    "Buns",
    "Cornrows",
    "Cornrows 2",
    "Flat Top",
    "Flat Top Long",
    "Gray Bun",
    "Gray Medium",
    "Gray Short",
    "hat-beanie",
    "hat-hip",
    "HeadAfro",
    "HeadBun",
    "HeadHijab",
    "HeadMohawk",
    "Long",
    "Long Afro",
    "Long Bangs",
    "Long Curly",
    "Medium 1",
    "Medium 2",
    "Medium 3",
    "Medium Bangs",
    "Medium Bangs 2",
    "Medium Bangs 3",
    "Medium Straight",
    "Mohawk 2",
    "No Hair 1",
    "No Hair 2",
    "No Hair 3",
    "Pomp",
    "Shaved 1",
    "Shaved 2",
    "Shaved 3",
    "Short 1",
    "Short 2",
    "Short 3",
    "Short 4",
    "Short 5",
    "Turban",
    "Twists",
    "Twists 2",
  ]

  static let faces: [String] = [
    "Angry with Fang",
    "Awe",
    "Blank",
    "Concerned",
    "Concerned Fear",
    "Contempt",
    "Cyclops",
    "Driven",
    "Eating Happy",
    "Explaining",
    "Eyes Closed",
    "FaceCalm",
    "FaceCheeky",
    "FaceCute",
    "FaceSmile",
    "Fear",
    "Hectic",
    "Loving Grin 1",
    "Loving Grin 2",
    "Monster",
    "Old",
    "Rage",
    "Serious",
    "Smile Big",
    "Smile LOL",
    "Smile Teeth Gap",
    "Solemn",
    "Suspicious",
    "Tired",
    "Very Angry",
  ]

  // Accessories removed - no longer used
}

